///
/// @Generated by Mockolo
///



import AuthenticationServices
import Foundation
import UIKit
@testable import UberAuth
@testable import UberCore


public class TokenManagingMock: TokenManaging {
    public init() { }


    public private(set) var saveTokenCallCount = 0
    public var saveTokenHandler: ((AccessToken, String, String?) -> (Bool))?
    public func saveToken(_ token: AccessToken, identifier: String, accessGroup: String?) -> Bool {
        saveTokenCallCount += 1
        if let saveTokenHandler = saveTokenHandler {
            return saveTokenHandler(token, identifier, accessGroup)
        }
        return false
    }

    public private(set) var getTokenCallCount = 0
    public var getTokenHandler: ((String, String?) -> (AccessToken?))?
    public func getToken(identifier: String, accessGroup: String?) -> AccessToken? {
        getTokenCallCount += 1
        if let getTokenHandler = getTokenHandler {
            return getTokenHandler(identifier, accessGroup)
        }
        return nil
    }

    public private(set) var deleteTokenCallCount = 0
    public var deleteTokenHandler: ((String, String?) -> (Bool))?
    public func deleteToken(identifier: String, accessGroup: String?) -> Bool {
        deleteTokenCallCount += 1
        if let deleteTokenHandler = deleteTokenHandler {
            return deleteTokenHandler(identifier, accessGroup)
        }
        return false
    }
}

class NetworkProvidingMock: NetworkProviding {
    init() { }


    private(set) var executeCallCount = 0
    var executeHandler: ((Any, Any) -> ())?
    func execute<R: NetworkRequest>(request: R, completion: @escaping (Result<R.Response, UberAuthError>) -> ())  {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            executeHandler(request, completion)
        }
        
    }
}

public class KeychainUtilityProtocolMock: KeychainUtilityProtocol {
    public init() { }


    public private(set) var saveCallCount = 0
    public var saveHandler: ((Any, String, String?) -> (Bool))?
    public func save<V: Encodable>(_ value: V, for key: String, accessGroup: String?) -> Bool {
        saveCallCount += 1
        if let saveHandler = saveHandler {
            return saveHandler(value, key, accessGroup)
        }
        return false
    }

    public private(set) var getCallCount = 0
    public var getHandler: ((String, String?) -> (Any?))?
    public func get<V: Decodable>(key: String, accessGroup: String?) -> V? {
        getCallCount += 1
        if let getHandler = getHandler {
            return getHandler(key, accessGroup) as? V
        }
        return nil
    }

    public private(set) var deleteCallCount = 0
    public var deleteHandler: ((String, String?) -> (Bool))?
    public func delete(key: String, accessGroup: String?) -> Bool {
        deleteCallCount += 1
        if let deleteHandler = deleteHandler {
            return deleteHandler(key, accessGroup)
        }
        return false
    }
}

class AuthorizationCodeResponseParsingMock: AuthorizationCodeResponseParsing {
    init() { }


    private(set) var isValidResponseCallCount = 0
    var isValidResponseHandler: ((URL, String) -> (Bool))?
    func isValidResponse(url: URL, matching redirectURI: String) -> Bool {
        isValidResponseCallCount += 1
        if let isValidResponseHandler = isValidResponseHandler {
            return isValidResponseHandler(url, redirectURI)
        }
        return false
    }

    private(set) var callAsFunctionCallCount = 0
    var callAsFunctionHandler: ((URL) -> (Result<Client, UberAuthError>))?
    func callAsFunction(url: URL) -> Result<Client, UberAuthError> {
        callAsFunctionCallCount += 1
        if let callAsFunctionHandler = callAsFunctionHandler {
            return callAsFunctionHandler(url)
        }
        fatalError("callAsFunctionHandler returns can't have a default value thus its handler must be set")
    }
}

public class ApplicationLaunchingMock: ApplicationLaunching {
    public init() { }


    public private(set) var launchCallCount = 0
    public var launchHandler: ((URL, ((Bool) -> ())?) -> ())?
    public func launch(_ url: URL, completion: ((Bool) -> ())?)  {
        launchCallCount += 1
        if let launchHandler = launchHandler {
            launchHandler(url, completion)
        }
        
    }
}

public class ConfigurationProvidingMock: ConfigurationProviding {
    public init() { }
    public init(clientID: String = "", redirectURI: String = "", sdkVersion: String = "", serverToken: String? = nil) {
        self.clientID = clientID
        self.redirectURI = redirectURI
        self.sdkVersion = sdkVersion
        self.serverToken = serverToken
    }


    public private(set) var clientIDSetCallCount = 0
    public var clientID: String = "" { didSet { clientIDSetCallCount += 1 } }

    public private(set) var redirectURISetCallCount = 0
    public var redirectURI: String = "" { didSet { redirectURISetCallCount += 1 } }

    public private(set) var sdkVersionSetCallCount = 0
    public var sdkVersion: String = "" { didSet { sdkVersionSetCallCount += 1 } }

    public private(set) var serverTokenSetCallCount = 0
    public var serverToken: String? = nil { didSet { serverTokenSetCallCount += 1 } }

    public static private(set) var isSandboxSetCallCount = 0
    static private var _isSandbox: Bool = false { didSet { isSandboxSetCallCount += 1 } }
    public static var isSandbox: Bool {
        get { return _isSandbox }
        set { _isSandbox = newValue }
    }

    public private(set) var isInstalledCallCount = 0
    public var isInstalledHandler: ((UberApp, Bool) -> (Bool))?
    public func isInstalled(app: UberApp, defaultIfUnregistered: Bool) -> Bool {
        isInstalledCallCount += 1
        if let isInstalledHandler = isInstalledHandler {
            return isInstalledHandler(app, defaultIfUnregistered)
        }
        return false
    }
}

class AuthenticationSessioningMock: AuthenticationSessioning {
        private var _anchor: ASPresentationAnchor!
    private var _callbackURLScheme: String!
    private var _completion: AuthCompletion!
    private var _url: URL!
    init() { }
    required init(anchor: ASPresentationAnchor, callbackURLScheme: String = "", url: URL = URL(fileURLWithPath: ""), completion: @escaping AuthCompletion) {
        self._anchor = anchor
        self._callbackURLScheme = callbackURLScheme
        self._url = url
        self._completion = completion
    }


    private(set) var startCallCount = 0
    var startHandler: (() -> ())?
    func start()  {
        startCallCount += 1
        if let startHandler = startHandler {
            startHandler()
        }
        
    }
}

public class AuthProvidingMock: AuthProviding {
    public init() { }
    public init(isLoggedIn: Bool = false) {
        self.isLoggedIn = isLoggedIn
    }


    public private(set) var executeCallCount = 0
    public var executeHandler: ((AuthDestination, Prefill?, @escaping (Result<Client, UberAuthError>) -> ()) -> ())?
    public func execute(authDestination: AuthDestination, prefill: Prefill?, completion: @escaping (Result<Client, UberAuthError>) -> ())  {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            executeHandler(authDestination, prefill, completion)
        }
        
    }

    public private(set) var logoutCallCount = 0
    public var logoutHandler: (() -> (Bool))?
    public func logout() -> Bool {
        logoutCallCount += 1
        if let logoutHandler = logoutHandler {
            return logoutHandler()
        }
        return false
    }

    public private(set) var handleCallCount = 0
    public var handleHandler: ((URL) -> (Bool))?
    public func handle(response url: URL) -> Bool {
        handleCallCount += 1
        if let handleHandler = handleHandler {
            return handleHandler(url)
        }
        return false
    }

    public private(set) var isLoggedInSetCallCount = 0
    public var isLoggedIn: Bool = false { didSet { isLoggedInSetCallCount += 1 } }
}

public class UberAuthInterfaceMock: UberAuthInterface {
    public init() { }


    public static private(set) var loginCallCount = 0
    public static var loginHandler: ((AuthContext, @escaping AuthCompletion) -> ())?
    public static func login(context: AuthContext, completion: @escaping AuthCompletion)  {
        loginCallCount += 1
        if let loginHandler = loginHandler {
            loginHandler(context, completion)
        }
        
    }

    public static private(set) var logoutCallCount = 0
    public static var logoutHandler: (() -> ())?
    public static func logout()  {
        logoutCallCount += 1
        if let logoutHandler = logoutHandler {
            logoutHandler()
        }
        
    }

    public static private(set) var handleCallCount = 0
    public static var handleHandler: ((URL) -> (Bool))?
    public static func handle(_ url: URL) -> Bool {
        handleCallCount += 1
        if let handleHandler = handleHandler {
            return handleHandler(url)
        }
        return false
    }
}

class AuthManagingMock: AuthManaging {
    init() { }
    init(isLoggedIn: Bool = false) {
        self.isLoggedIn = isLoggedIn
    }


    private(set) var loginCallCount = 0
    var loginHandler: ((AuthContext, @escaping AuthCompletion) -> ())?
    func login(context: AuthContext, completion: @escaping AuthCompletion)  {
        loginCallCount += 1
        if let loginHandler = loginHandler {
            loginHandler(context, completion)
        }
        
    }

    private(set) var logoutCallCount = 0
    var logoutHandler: (() -> ())?
    func logout()  {
        logoutCallCount += 1
        if let logoutHandler = logoutHandler {
            logoutHandler()
        }
        
    }

    private(set) var handleCallCount = 0
    var handleHandler: ((URL) -> (Bool))?
    func handle(_ url: URL) -> Bool {
        handleCallCount += 1
        if let handleHandler = handleHandler {
            return handleHandler(url)
        }
        return false
    }

    private(set) var isLoggedInSetCallCount = 0
    var isLoggedIn: Bool = false { didSet { isLoggedInSetCallCount += 1 } }
}

