///
/// @Generated by Mockolo
///



import AuthenticationServices
import Foundation
import UIKit
@testable import UberAuth
@testable import UberCore


public final class TokenManagingMock: TokenManaging {
    public init() { }


    public private(set) var saveTokenCallCount = 0
    public var saveTokenHandler: ((AccessToken, String, String?) -> Bool)?
    public func saveToken(_ token: AccessToken, identifier: String, accessGroup: String?) -> Bool {
        saveTokenCallCount += 1
        if let saveTokenHandler = saveTokenHandler {
            return saveTokenHandler(token, identifier, accessGroup)
        }
        return false
    }

    public private(set) var getTokenCallCount = 0
    public var getTokenHandler: ((String, String?) -> AccessToken?)?
    public func getToken(identifier: String, accessGroup: String?) -> AccessToken? {
        getTokenCallCount += 1
        if let getTokenHandler = getTokenHandler {
            return getTokenHandler(identifier, accessGroup)
        }
        return nil
    }

    public private(set) var deleteTokenCallCount = 0
    public var deleteTokenHandler: ((String, String?) -> Bool)?
    public func deleteToken(identifier: String, accessGroup: String?) -> Bool {
        deleteTokenCallCount += 1
        if let deleteTokenHandler = deleteTokenHandler {
            return deleteTokenHandler(identifier, accessGroup)
        }
        return false
    }
}

public final class KeychainUtilityProtocolMock: KeychainUtilityProtocol {
    public init() { }


    public private(set) var saveCallCount = 0
    public var saveHandler: ((Any, String, String?) -> Bool)?
    public func save<V: Encodable>(_ value: V, for key: String, accessGroup: String?) -> Bool {
        saveCallCount += 1
        if let saveHandler = saveHandler {
            return saveHandler(value, key, accessGroup)
        }
        return false
    }

    public private(set) var getCallCount = 0
    public var getHandler: ((String, String?) -> Any?)?
    public func get<V: Decodable>(key: String, accessGroup: String?) -> V? {
        getCallCount += 1
        if let getHandler = getHandler {
            return getHandler(key, accessGroup) as? V
        }
        return nil
    }

    public private(set) var deleteCallCount = 0
    public var deleteHandler: ((String, String?) -> Bool)?
    public func delete(key: String, accessGroup: String?) -> Bool {
        deleteCallCount += 1
        if let deleteHandler = deleteHandler {
            return deleteHandler(key, accessGroup)
        }
        return false
    }
}

final class NetworkProvidingMock: NetworkProviding {
    init() { }

    private(set) var executeCallCount = 0
    var executeHandler: ((Any, Any) -> ())?
    func execute<R: NetworkRequest>(request: R, completion: @escaping (Result<R.Response, UberAuthError>) -> ()) {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            executeHandler(request, completion)
        }
        
    }
    
    var executeAsyncResult: Result<Any, Error>?
    func execute<R: NetworkRequest>(request: R) async throws -> R.Response {
        executeCallCount += 1
        
        guard let result = executeAsyncResult else { throw UberAuthError.serviceError }
        
        switch result {
        case .success(let response):
            guard let typedResponse = response as? R.Response else { throw UberAuthError.serviceError }
            return typedResponse
        case .failure(let error):
            throw error
        }
    }
}

final class AuthorizationCodeResponseParsingMock: AuthorizationCodeResponseParsing {
    init() { }


    private(set) var isValidResponseCallCount = 0
    var isValidResponseHandler: ((URL, String) -> Bool)?
    func isValidResponse(url: URL, matching redirectURI: String) -> Bool {
        isValidResponseCallCount += 1
        if let isValidResponseHandler = isValidResponseHandler {
            return isValidResponseHandler(url, redirectURI)
        }
        return false
    }

    private(set) var callAsFunctionCallCount = 0
    var callAsFunctionHandler: ((URL) -> Result<Client, UberAuthError>)?
    func callAsFunction(url: URL) -> Result<Client, UberAuthError> {
        callAsFunctionCallCount += 1
        if let callAsFunctionHandler = callAsFunctionHandler {
            return callAsFunctionHandler(url)
        }
        fatalError("callAsFunctionHandler returns can't have a default value thus its handler must be set")
    }
}

public final class ApplicationLaunchingMock: ApplicationLaunching {
    public init() { }


    public private(set) var launchCallCount = 0
    public var launchHandler: ((URL, ((Bool) -> ())?) -> ())?
    public func launch(_ url: URL, completion: ((Bool) -> ())?) {
        launchCallCount += 1
        if let launchHandler = launchHandler {
            launchHandler(url, completion)
        }
        
    }

    public private(set) var launchUrlCallCount = 0
    public var launchResult: Bool = false
    public func launch(_ url: URL) async -> Bool {
        launchUrlCallCount += 1
        return launchResult
    }
}

public final class ConfigurationProvidingMock: ConfigurationProviding {
    public init() { }
    public init(clientID: String = "", redirectURI: String = "", sdkVersion: String = "", serverToken: String? = nil) {
        self.clientID = clientID
        self.redirectURI = redirectURI
        self.sdkVersion = sdkVersion
        self.serverToken = serverToken
    }



    public var clientID: String = ""


    public var redirectURI: String = ""


    public var sdkVersion: String = ""


    public var serverToken: String? = nil


    public static var isSandbox: Bool = false

    public private(set) var isInstalledCallCount = 0
    public var isInstalledHandler: ((UberApp, Bool) -> Bool)?
    public func isInstalled(app: UberApp, defaultIfUnregistered: Bool) -> Bool {
        isInstalledCallCount += 1
        if let isInstalledHandler = isInstalledHandler {
            return isInstalledHandler(app, defaultIfUnregistered)
        }
        return false
    }
}

final class AuthenticationSessioningMock: AuthenticationSessioning {
    private var _anchor: ASPresentationAnchor!
    private var _callbackURLScheme: String!
    private var _completion: AuthCompletion!
    private var _url: URL!
    init() { }
    required init(anchor: ASPresentationAnchor, callbackURLScheme: String = "", url: URL = URL(fileURLWithPath: ""), pendingState: String? = nil, completion: @escaping AuthCompletion) {
        self._anchor = anchor
        self._callbackURLScheme = callbackURLScheme
        self._url = url
        self._completion = completion
    }


    private(set) var startCallCount = 0
    var startHandler: (() -> ())?
    func start() {
        startCallCount += 1
        if let startHandler = startHandler {
            startHandler()
        }
        
    }
}

public final class AuthProvidingMock: AuthProviding {
    public init() { }
    public init(isLoggedIn: Bool = false) {
        self.isLoggedIn = isLoggedIn
    }


    public private(set) var executeCallCount = 0
    public var executeHandler: ((AuthDestination, Prefill?, @escaping (Result<Client, UberAuthError>) -> ()) -> ())?
    public func execute(authDestination: AuthDestination, prefill: Prefill?, completion: @escaping (Result<Client, UberAuthError>) -> ()) {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            executeHandler(authDestination, prefill, completion)
        }
        
    }
    
    public var executeAsyncResult: Result<Client, Error>?
    public func execute(authDestination: AuthDestination, prefill: Prefill?) async throws -> Client {
        executeCallCount += 1
        
        guard let result = executeAsyncResult else { throw UberAuthError.serviceError }
        
        switch result {
        case .success(let client):
            return client
        case .failure(let error):
            throw error
        }
    }

    public private(set) var logoutCallCount = 0
    public var logoutHandler: (() -> Bool)?
    public func logout() -> Bool {
        logoutCallCount += 1
        if let logoutHandler = logoutHandler {
            return logoutHandler()
        }
        return false
    }

    public private(set) var handleCallCount = 0
    public var handleHandler: ((URL) -> Bool)?
    public func handle(response url: URL) -> Bool {
        handleCallCount += 1
        if let handleHandler = handleHandler {
            return handleHandler(url)
        }
        return false
    }

    public var isLoggedIn: Bool = false
}

public final class UberAuthInterfaceMock: UberAuthInterface {
    public init() { }

    public static private(set) var loginCallCount = 0
    public static var loginHandler: ((AuthContext, @escaping AuthCompletion) -> ())?
    public static func login(context: AuthContext, completion: @escaping AuthCompletion) {
        loginCallCount += 1
        if let loginHandler = loginHandler {
            loginHandler(context, completion)
        }
        
    }
    
    public static var loginAsyncResult: Result<Client, Error>?
    public static func login(context: AuthContext) async throws -> Client {
        loginCallCount += 1
        
        guard let result = loginAsyncResult else { throw UberAuthError.serviceError }
        
        switch result {
        case .success(let client):
            return client
        case .failure(let error):
            throw error
        }
    }

    public static private(set) var logoutCallCount = 0
    public static var logoutHandler: (() -> ())?
    public static func logout() {
        logoutCallCount += 1
        if let logoutHandler = logoutHandler {
            logoutHandler()
        }
        
    }

    public static private(set) var handleCallCount = 0
    public static var handleHandler: ((URL) -> Bool)?
    public static func handle(_ url: URL) -> Bool {
        handleCallCount += 1
        if let handleHandler = handleHandler {
            return handleHandler(url)
        }
        return false
    }
}

final class AuthManagingMock: AuthManaging {
    init() { }
    init(isLoggedIn: Bool = false) {
        self.isLoggedIn = isLoggedIn
    }

    private(set) var loginCallCount = 0
    var loginHandler: ((AuthContext, @escaping AuthCompletion) -> ())?
    func login(context: AuthContext, completion: @escaping AuthCompletion) {
        loginCallCount += 1
        if let loginHandler = loginHandler {
            loginHandler(context, completion)
        }
        
    }
    
    var loginAsyncResult: Result<Client, Error>?
    func login(context: AuthContext) async throws -> Client {
        loginCallCount += 1
        
        guard let result = loginAsyncResult else { throw UberAuthError.serviceError }
        
        switch result {
        case .success(let client):
            return client
        case .failure(let error):
            throw error
        }
    }

    private(set) var logoutCallCount = 0
    var logoutHandler: (() -> ())?
    func logout() {
        logoutCallCount += 1
        if let logoutHandler = logoutHandler {
            logoutHandler()
        }
        
    }

    private(set) var handleCallCount = 0
    var handleHandler: ((URL) -> Bool)?
    func handle(_ url: URL) -> Bool {
        handleCallCount += 1
        if let handleHandler = handleHandler {
            return handleHandler(url)
        }
        return false
    }

    var isLoggedIn: Bool = false
}
